# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tests/protobuf/test.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "tests/protobuf/test.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19tests/protobuf/test.proto"\x1f\n\x07Request\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05"\x15\n\x08Response\x12\t\n\x01\x63\x18\x01 \x01(\x05"\x07\n\x05\x45mpty2A\n\x04Math\x12\x1c\n\x03Sum\x12\x08.Request\x1a\t.Response"\x00\x12\x1b\n\x05\x43lear\x12\x08.Request\x1a\x06.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tests.protobuf.test_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REQUEST"]._serialized_start = 29
    _globals["_REQUEST"]._serialized_end = 60
    _globals["_RESPONSE"]._serialized_start = 62
    _globals["_RESPONSE"]._serialized_end = 83
    _globals["_EMPTY"]._serialized_start = 85
    _globals["_EMPTY"]._serialized_end = 92
    _globals["_MATH"]._serialized_start = 94
    _globals["_MATH"]._serialized_end = 159
# @@protoc_insertion_point(module_scope)
