# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from tests.protobuf import test_pb2 as tests_dot_protobuf_dot_test__pb2

GRPC_GENERATED_VERSION = "1.69.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in tests/protobuf/test_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MathStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sum = channel.unary_unary(
            "/Math/Sum",
            request_serializer=tests_dot_protobuf_dot_test__pb2.Request.SerializeToString,
            response_deserializer=tests_dot_protobuf_dot_test__pb2.Response.FromString,
            _registered_method=True,
        )
        self.Clear = channel.unary_unary(
            "/Math/Clear",
            request_serializer=tests_dot_protobuf_dot_test__pb2.Request.SerializeToString,
            response_deserializer=tests_dot_protobuf_dot_test__pb2.Empty.FromString,
            _registered_method=True,
        )


class MathServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Clear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MathServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Sum": grpc.unary_unary_rpc_method_handler(
            servicer.Sum,
            request_deserializer=tests_dot_protobuf_dot_test__pb2.Request.FromString,
            response_serializer=tests_dot_protobuf_dot_test__pb2.Response.SerializeToString,
        ),
        "Clear": grpc.unary_unary_rpc_method_handler(
            servicer.Clear,
            request_deserializer=tests_dot_protobuf_dot_test__pb2.Request.FromString,
            response_serializer=tests_dot_protobuf_dot_test__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("Math", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("Math", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Math(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sum(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Math/Sum",
            tests_dot_protobuf_dot_test__pb2.Request.SerializeToString,
            tests_dot_protobuf_dot_test__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Clear(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Math/Clear",
            tests_dot_protobuf_dot_test__pb2.Request.SerializeToString,
            tests_dot_protobuf_dot_test__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
